# Generated by Django 5.1.7 on 2025-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0012_alter_tariff_power_generation_tusd_in_reais_per_kw'),
        ('universities', '0015_alter_consumerunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('university', 'cnpj'), name='unique_distributor_university_cnpj'),
        ),
    ]
