# Generated by Django 5.1.8 on 2025-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0013_alter_distributor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distributor',
            name='unique_distributor_university_cnpj',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='university',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
    ]
