# Generated by Django 5.1.8 on 2025-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0014_remove_distributor_unique_distributor_university_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
