# Generated by Django 5.1.7 on 2025-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('super_user', 'super_user'), ('university_admin', 'university_admin'), ('university_user', 'university_user'), ('university_guest', 'university_guest')], max_length=25),
        ),
    ]
