# Generated by Django 5.1.7 on 2025-04-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_alter_consumerunit_unique_together_and_more'),
        ('users', '0014_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='university',
            field=models.ForeignKey(help_text='Um Usuário de Universidade deve estar ligado a uma Universidade', null=True, on_delete=django.db.models.deletion.PROTECT, to='universities.university', verbose_name='Universidade'),
        ),
    ]
