# Generated by Django 5.1.9 on 2025-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_universityuser_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('super_user', 'super_user'), ('university_admin', 'university_admin'), ('university_user', 'university_user'), ('university_guest', 'university_guest'), ('university_viewer', 'university_viewer')], max_length=25),
        ),
    ]
