# Generated by Django 5.1.1 on 2024-10-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_energybill_off_peak_consumption_in_kwh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='supply_voltage',
        ),
    ]
