# Generated by Django 5.1.2 on 2024-11-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_remove_contract_supply_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='off_peak_contracted_demand_in_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='peak_contracted_demand_in_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
