# Generated by Django 5.1.3 on 2024-12-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_commons', '0001_initial'),
        ('universities', '0015_alter_consumerunit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='consume_unit_id',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='consumer_unit_id',
            field=models.ForeignKey(help_text='Recomendações devem estar ligadas a Unidades Consumidoras', null=True, on_delete=django.db.models.deletion.PROTECT, to='universities.consumerunit'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='hist_init_date',
            field=models.DateField(help_text='Data de ínício da análise no histórico', null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='hist_start_date',
            field=models.DateField(help_text='Data de fim da análise no histórico', null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='current_off_peak_demand',
            field=models.IntegerField(help_text='Demanda fora de ponta do contrato atual', null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='current_peak_demand',
            field=models.IntegerField(help_text='Demanda ponta do contrato atual', null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='current_tariff_flag',
            field=models.CharField(choices=[('G', 'Verde'), ('B', 'Azul')], help_text='Modalidade tarifária do contrato atual', max_length=1),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='current_total_value',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do contrato atual', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_off_peak_demand',
            field=models.IntegerField(help_text='Demanda fora de ponta recomendada', null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_peak_demand',
            field=models.IntegerField(help_text='Demanda ponta recomendada', null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_tariff_flag',
            field=models.CharField(choices=[('G', 'Verde'), ('B', 'Azul')], help_text='Modalidade tarifária recomendada', max_length=1),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_total_value',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do contrato recomendado', max_digits=10, null=True),
        ),
    ]
