# Generated by Django 5.1.3 on 2024-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_alter_consumerunit_name_alter_university_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumerunit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='consumerunit',
            constraint=models.UniqueConstraint(fields=('university', 'code'), name='unique_consumer_unit_university_code'),
        ),
        migrations.AddConstraint(
            model_name='consumerunit',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_consumer_unit_university_name'),
        ),
    ]
