# Generated by Django 5.1.8 on 2025-04-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_alter_consumerunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
