# Generated by Django 5.1.8 on 2025-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0014_remove_distributor_unique_distributor_university_cnpj_and_more'),
        ('universities', '0016_alter_university_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='distributors',
            field=models.ManyToManyField(blank=True, related_name='universities', to='tariffs.distributor'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Código da Unidade Consumidora'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='total_installed_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='acronym',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='university',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
