# Generated by Django 5.1.7 on 2025-04-16 09:43

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0016_alter_contract_off_peak_contracted_demand_in_kw_and_more'),
        ('universities', '0015_alter_consumerunit_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('consumer_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='universities.consumerunit')),
                ('isValid', models.BooleanField(blank=True, null=True)),
                ('generatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('energyBillsCount', models.IntegerField(blank=True, null=True)),
                ('currentTotalCost', models.FloatField(blank=True, null=True)),
                ('shouldRenewContract', models.BooleanField(blank=True, null=True)),
                ('nominalSavingsPercentage', models.FloatField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=None)),
                ('errors', models.JSONField(null=True)),
                ('warnings', models.JSONField(null=True)),
                ('tariffStartDate', models.DateField(null=True)),
                ('tariffEndDate', models.DateField(null=True)),
                ('costsComparisonPlot', models.JSONField(null=True)),
                ('recommendedContract', models.JSONField(null=True)),
                ('currentContractCostsPlot', models.JSONField(null=True)),
                ('contractsComparisonTotals', models.JSONField(null=True)),
                ('detailedContractsCostsComparisonPlot', models.JSONField(null=True)),
                ('currentContract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
    ]
